/**
 * Application constants and configuration
 */

import {
  Code2,
  Database,
  Cloud,
  Layers,
  Terminal,
  Cpu,
  Globe,
  Server,
  Lock,
  Zap,
  GitBranch,
  Box,
  Brain,
  Palette,
  Smartphone,
  LineChart,
  Shield,
  Rocket,
  Wifi,
  Users,
  MessageSquare,
  ChevronRight,
  Mail,
  Phone,
  MapPin,
  Github,
  Linkedin,
  Twitter,
  Instagram,
  ExternalLink,
  Eye,
  Heart,
  Star,
  Award,
  Clock,
  Calendar,
  CheckCircle,
  X,
  Menu,
  ChevronDown,
  Sun,
  Moon,
  Laptop,
  Search,
  Filter,
  SortAsc,
  SortDesc,
  Download,
  Upload,
  Settings,
  HelpCircle,
  Info,
  AlertCircle,
  Check,
  Copy,
  Edit,
  Trash,
  Plus,
  Minus,
  XCircle,
  User,
  LogOut,
  Home,
  Briefcase,
  BookOpen,
  Command,
  CreditCard,
  BarChart,
  PieChart,
  TrendingUp,
  Bell,
  Inbox,
  Folder,
  FileText,
  Image,
  Video,
  Music,
  Film,
  Camera,
  Mic,
  Headphones,
  Printer,
  Share2,
  ThumbsUp,
  MessageCircle,
  Send,
  Save,
  RefreshCw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Grid,
  List,
  Layout,
  Sidebar,
  Tablet,
  Smartphone as PhoneIcon,
  Monitor,
  Watch,
  Battery,
  Wifi as WifiIcon,
  Bluetooth,
  HardDrive,
  Cpu as CpuIcon,
  MemoryStick,
  Mouse,
  Keyboard,
  Speaker,
  Webcam,
  Router,
  Database as DatabaseIcon,
  Cloud as CloudIcon,
  Server as ServerIcon,
  Code,
  Terminal as TerminalIcon,
  GitMerge,
  GitPullRequest,
  GitCommit,
  Bug,
  TestTube,
  Flask,
  Beaker,
  Microscope,
  Atom,
  Cpu as Chip,
  CircuitBoard,
  Cpu as Processor,
  BrainCircuit,
  Network,
  Shield as ShieldIcon,
  Lock as LockIcon,
  Key,
  Fingerprint,
  EyeOff,
  QrCode,
  Scan,
  Camera as CameraIcon,
  Video as VideoIcon,
  Mic as MicIcon,
  Headphones as HeadphonesIcon,
  Radio,
  Satellite,
  Radar,
  Telescope,
  Compass,
  Map,
  Navigation,
  Globe as GlobeIcon,
  MapPin as MapPinIcon,
  Navigation2,
  Flag,
  Anchor,
  Ship,
  Plane,
  Car,
  Bike,
  Train,
  Bus,
  Rocket as RocketIcon,
  Satellite as SatelliteIcon,
} from "lucide-react";

// Application configuration
export const APP_CONFIG = {
  name: "Yohannes Belete",
  title: "Senior Full-Stack Developer & System Architect",
  description:
    "Building exceptional digital experiences with modern technologies. Specializing in full-stack development, cloud architecture, and performance optimization.",
  url: "https://yohannesbelete.dev",
  author: "Yohannes Belete",
  email: "hello@yohannesbelete.dev",
  location: "San Francisco, CA",
  phone: "+1 (555) 123-4567",
  copyright: `© ${new Date().getFullYear()} Yohannes Belete. All rights reserved.`,
  version: "1.0.0",
  environment: process.env.NODE_ENV || "development",
  isProduction: process.env.NODE_ENV === "production",
} as const;

// Navigation items
export const NAVIGATION = [
  {
    id: "home",
    name: "Home",
    href: "#home",
    icon: Home,
    description: "Welcome section",
  },
  {
    id: "about",
    name: "About",
    href: "#about",
    icon: User,
    description: "About me section",
  },

  {
    id: "skills",
    name: "Skills",
    href: "#skills",
    icon: Code,
    description: "Technical skills section",
  },
  {
    id: "projects",
    name: "Projects",
    href: "#projects",
    icon: Briefcase,
    description: "Projects showcase",
  },
  {
    id: "contact",
    name: "Contact",
    href: "#contact",
    icon: MessageSquare,
    description: "Contact information",
  },
] as const;

// Social media links
export const SOCIAL_LINKS = [
  {
    platform: "GitHub",
    url: "https://github.com/yohannesbelete",
    icon: Github,
    label: "GitHub Profile",
    color: "bg-gray-900 hover:bg-gray-800",
    textColor: "text-white",
  },
  {
    platform: "LinkedIn",
    url: "https://linkedin.com/in/yohannesbelete",
    icon: Linkedin,
    label: "LinkedIn Profile",
    color: "bg-blue-700 hover:bg-blue-600",
    textColor: "text-white",
  },
  {
    platform: "Twitter",
    url: "https://twitter.com/yohannesbelete",
    icon: Twitter,
    label: "Twitter Profile",
    color: "bg-sky-500 hover:bg-sky-400",
    textColor: "text-white",
  },
  {
    platform: "Instagram",
    url: "https://instagram.com/yohannesbelete",
    icon: Instagram,
    label: "Instagram Profile",
    color:
      "bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600",
    textColor: "text-white",
  },
  {
    platform: "Email",
    url: "mailto:hello@yohannesbelete.dev",
    icon: Mail,
    label: "Send Email",
    color: "bg-green-600 hover:bg-green-500",
    textColor: "text-white",
  },
] as const;

// Skill categories
export const SKILL_CATEGORIES = [
  {
    id: "frontend",
    label: "Frontend Development",
    icon: Globe,
    color: "primary",
    description: "Building responsive and interactive user interfaces",
    gradient: "from-emerald-500 to-green-500",
  },
  {
    id: "backend",
    label: "Backend Development",
    icon: Server,
    color: "secondary",
    description: "Developing robust server-side applications",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "devops",
    label: "DevOps & Cloud",
    icon: Cloud,
    color: "accent",
    description: "Deploying and maintaining scalable infrastructure",
    gradient: "from-violet-500 to-purple-500",
  },
  {
    id: "tools",
    label: "Development Tools",
    icon: Box,
    color: "primary",
    description: "Development tools and technologies",
    gradient: "from-emerald-500 to-cyan-500",
  },
  {
    id: "soft",
    label: "Soft Skills",
    icon: Brain,
    color: "secondary",
    description: "Professional and interpersonal abilities",
    gradient: "from-amber-500 to-rose-500",
  },
  {
    id: "design",
    label: "UI/UX Design",
    icon: Palette,
    color: "accent",
    description: "User interface and experience design",
    gradient: "from-violet-500 to-pink-500",
  },
] as const;

// Skills data
export const SKILLS_DATA = {
  frontend: [
    {
      name: "React / Next.js",
      level: 98,
      icon: Code2,
      description: "Building modern web applications with React ecosystem",
      color: "bg-gradient-to-r from-blue-500 to-cyan-500",
      experience: "5+ years",
      projects: 24,
    },
    {
      name: "TypeScript",
      level: 95,
      icon: Code2,
      description: "Type-safe JavaScript development",
      color: "bg-gradient-to-r from-blue-600 to-blue-400",
      experience: "4+ years",
      projects: 18,
    },
    {
      name: "Vue.js / Nuxt.js",
      level: 88,
      icon: Globe,
      description: "Progressive framework expertise",
      color: "bg-gradient-to-r from-green-500 to-emerald-500",
      experience: "3+ years",
      projects: 12,
    },
    {
      name: "Tailwind CSS",
      level: 96,
      icon: Palette,
      description: "Utility-first CSS framework",
      color: "bg-gradient-to-r from-cyan-500 to-teal-500",
      experience: "4+ years",
      projects: 32,
    },
    {
      name: "Animation Libraries",
      level: 92,
      icon: Layers,
      description: "Creating smooth animations and interactions",
      color: "bg-gradient-to-r from-purple-500 to-pink-500",
      experience: "3+ years",
      projects: 16,
    },
    {
      name: "Three.js / WebGL",
      level: 85,
      icon: Box,
      description: "3D graphics and visualization",
      color: "bg-gradient-to-r from-gray-800 to-gray-600",
      experience: "2+ years",
      projects: 8,
    },
    {
      name: "React Native",
      level: 82,
      icon: Smartphone,
      description: "Cross-platform mobile development",
      color: "bg-gradient-to-r from-blue-400 to-indigo-500",
      experience: "2+ years",
      projects: 6,
    },
  ],
  backend: [
    {
      name: "Node.js / Express",
      level: 96,
      icon: Server,
      description: "Server-side JavaScript runtime",
      color: "bg-gradient-to-r from-green-600 to-lime-500",
      experience: "5+ years",
      projects: 28,
    },
    {
      name: "Python / Django",
      level: 90,
      icon: Terminal,
      description: "Full-stack Python framework",
      color: "bg-gradient-to-r from-blue-800 to-cyan-600",
      experience: "4+ years",
      projects: 14,
    },
    {
      name: "Go",
      level: 85,
      icon: Cpu,
      description: "High-performance systems programming",
      color: "bg-gradient-to-r from-cyan-700 to-blue-500",
      experience: "2+ years",
      projects: 9,
    },
    {
      name: "PostgreSQL",
      level: 94,
      icon: Database,
      description: "Advanced relational database",
      color: "bg-gradient-to-r from-blue-700 to-blue-500",
      experience: "4+ years",
      projects: 22,
    },
    {
      name: "MongoDB",
      level: 88,
      icon: DatabaseIcon,
      description: "NoSQL document database",
      color: "bg-gradient-to-r from-green-700 to-green-500",
      experience: "3+ years",
      projects: 15,
    },
    {
      name: "Redis",
      level: 90,
      icon: Database,
      description: "In-memory data structure store",
      color: "bg-gradient-to-r from-red-600 to-orange-500",
      experience: "3+ years",
      projects: 18,
    },
    {
      name: "GraphQL",
      level: 92,
      icon: GitBranch,
      description: "Query language for APIs",
      color: "bg-gradient-to-r from-pink-600 to-purple-500",
      experience: "3+ years",
      projects: 16,
    },
    {
      name: "REST APIs",
      level: 98,
      icon: MessageSquare,
      description: "Designing robust APIs",
      color: "bg-gradient-to-r from-green-600 to-emerald-500",
      experience: "5+ years",
      projects: 35,
    },
  ],
  devops: [
    {
      name: "AWS",
      level: 95,
      icon: Cloud,
      description: "Cloud infrastructure and services",
      color: "bg-gradient-to-r from-orange-500 to-yellow-500",
      experience: "4+ years",
      projects: 25,
    },
    {
      name: "Docker",
      level: 96,
      icon: Box,
      description: "Containerization platform",
      color: "bg-gradient-to-r from-blue-600 to-cyan-500",
      experience: "4+ years",
      projects: 28,
    },
    {
      name: "Kubernetes",
      level: 90,
      icon: Layers,
      description: "Container orchestration",
      color: "bg-gradient-to-r from-blue-700 to-blue-500",
      experience: "3+ years",
      projects: 14,
    },
    {
      name: "CI/CD",
      level: 94,
      icon: GitBranch,
      description: "Continuous integration/deployment",
      color: "bg-gradient-to-r from-green-600 to-emerald-500",
      experience: "4+ years",
      projects: 22,
    },
    {
      name: "Terraform",
      level: 88,
      icon: CloudIcon,
      description: "Infrastructure as code",
      color: "bg-gradient-to-r from-purple-600 to-pink-500",
      experience: "3+ years",
      projects: 12,
    },
    {
      name: "Monitoring",
      level: 92,
      icon: LineChart,
      description: "System observability and monitoring",
      color: "bg-gradient-to-r from-blue-500 to-indigo-500",
      experience: "3+ years",
      projects: 18,
    },
    {
      name: "Security",
      level: 89,
      icon: Shield,
      description: "Security best practices",
      color: "bg-gradient-to-r from-red-600 to-orange-500",
      experience: "3+ years",
      projects: 16,
    },
    {
      name: "Linux / Bash",
      level: 93,
      icon: TerminalIcon,
      description: "System administration and scripting",
      color: "bg-gradient-to-r from-gray-800 to-gray-600",
      experience: "5+ years",
      projects: 30,
    },
  ],
  tools: [
    {
      name: "Git / GitHub",
      level: 98,
      icon: GitBranch,
      description: "Version control and collaboration",
      color: "bg-gradient-to-r from-gray-900 to-gray-700",
      experience: "5+ years",
      projects: 40,
    },
    {
      name: "VS Code",
      level: 97,
      icon: Code2,
      description: "Code editor and extensions",
      color: "bg-gradient-to-r from-blue-600 to-cyan-500",
      experience: "5+ years",
      projects: 35,
    },
    {
      name: "Webpack / Vite",
      level: 91,
      icon: Box,
      description: "Build tools and bundlers",
      color: "bg-gradient-to-r from-yellow-600 to-amber-500",
      experience: "4+ years",
      projects: 20,
    },
    {
      name: "Jest / Cypress",
      level: 90,
      icon: Shield,
      description: "Testing frameworks",
      color: "bg-gradient-to-r from-red-600 to-orange-500",
      experience: "3+ years",
      projects: 18,
    },
    {
      name: "Figma",
      level: 85,
      icon: Palette,
      description: "Design and prototyping",
      color: "bg-gradient-to-r from-purple-600 to-pink-500",
      experience: "2+ years",
      projects: 12,
    },
    {
      name: "Postman",
      level: 94,
      icon: MessageSquare,
      description: "API development and testing",
      color: "bg-gradient-to-r from-orange-600 to-orange-400",
      experience: "3+ years",
      projects: 22,
    },
    {
      name: "Nginx",
      level: 87,
      icon: ServerIcon,
      description: "Web server and reverse proxy",
      color: "bg-gradient-to-r from-green-700 to-green-500",
      experience: "3+ years",
      projects: 15,
    },
  ],
  soft: [
    {
      name: "Problem Solving",
      level: 96,
      icon: Brain,
      description: "Analytical thinking and solutions",
      color: "bg-gradient-to-r from-indigo-600 to-purple-500",
      experience: "5+ years",
      projects: 35,
    },
    {
      name: "Communication",
      level: 94,
      icon: MessageSquare,
      description: "Clear and effective communication",
      color: "bg-gradient-to-r from-green-600 to-emerald-500",
      experience: "5+ years",
      projects: 30,
    },
    {
      name: "Leadership",
      level: 92,
      icon: Rocket,
      description: "Team leadership and mentoring",
      color: "bg-gradient-to-r from-orange-600 to-amber-500",
      experience: "4+ years",
      projects: 18,
    },
    {
      name: "Agile / Scrum",
      level: 95,
      icon: Layers,
      description: "Project management methodologies",
      color: "bg-gradient-to-r from-blue-600 to-cyan-500",
      experience: "4+ years",
      projects: 25,
    },
    {
      name: "Time Management",
      level: 93,
      icon: Zap,
      description: "Efficient task prioritization",
      color: "bg-gradient-to-r from-yellow-600 to-yellow-400",
      experience: "5+ years",
      projects: 32,
    },
    {
      name: "Collaboration",
      level: 97,
      icon: Users,
      description: "Team collaboration and coordination",
      color: "bg-gradient-to-r from-teal-600 to-cyan-500",
      experience: "5+ years",
      projects: 38,
    },
    {
      name: "Adaptability",
      level: 91,
      icon: RefreshCw,
      description: "Quick adaptation to new technologies",
      color: "bg-gradient-to-r from-violet-600 to-purple-500",
      experience: "5+ years",
      projects: 28,
    },
  ],
} as const;

// Skills overview statistics
export const SKILLS_OVERVIEW = [
  {
    category: "Frontend Development",
    icon: Globe,
    stats: [
      { label: "Frameworks", value: "React, Vue, Angular, Svelte" },
      { label: "Styling", value: "Tailwind, SCSS, CSS-in-JS, Styled" },
      { label: "State Management", value: "Redux, Context, Zustand, Pinia" },
      { label: "Performance", value: "Lighthouse 95+, Core Web Vitals" },
      { label: "Animation", value: "GSAP, Framer, Anime.js, Three.js" },
      { label: "Testing", value: "Jest, Testing Library, Cypress" },
    ],
    gradient: "from-emerald-500/20 via-green-500/10 to-emerald-500/5",
  },
  {
    category: "Backend Development",
    icon: Server,
    stats: [
      { label: "Languages", value: "Node.js, Python, Go, Java" },
      { label: "Databases", value: "PostgreSQL, MongoDB, Redis, MySQL" },
      { label: "APIs", value: "REST, GraphQL, WebSocket, gRPC" },
      { label: "Architecture", value: "Microservices, Monolith, Serverless" },
      { label: "Authentication", value: "JWT, OAuth2, Passport, Auth0" },
      { label: "Caching", value: "Redis, Memcached, CDN, Varnish" },
    ],
    gradient: "from-amber-500/20 via-orange-500/10 to-amber-500/5",
  },
  {
    category: "Infrastructure & DevOps",
    icon: Cloud,
    stats: [
      { label: "Cloud Platforms", value: "AWS, GCP, Azure, DigitalOcean" },
      { label: "Containers", value: "Docker, Kubernetes, Podman, ECS" },
      { label: "CI/CD", value: "GitHub Actions, Jenkins, GitLab, CircleCI" },
      { label: "Monitoring", value: "Prometheus, Grafana, Datadog, New Relic" },
      { label: "Security", value: "WAF, DDoS, SSL/TLS, Penetration Testing" },
      { label: "Infrastructure", value: "Terraform, Ansible, CloudFormation" },
    ],
    gradient: "from-violet-500/20 via-purple-500/10 to-violet-500/5",
  },
] as const;

// Projects data
export const PROJECT_CATEGORIES = [
  "All",
  "Full-Stack",
  "AI/ML",
  "Enterprise",
  "Mobile",
  "IoT",
  "Data Visualization",
  "E-commerce",
  "SaaS",
  "Open Source",
] as const;

// Contact information
export const CONTACT_INFO = [
  {
    type: "email",
    value: "hello@yohannesbelete.dev",
    label: "Email Address",
    icon: Mail,
    href: "mailto:hello@yohannesbelete.dev",
    description: "Send me an email",
    color: "bg-green-600 hover:bg-green-500",
  },
  {
    type: "phone",
    value: "+1 (555) 123-4567",
    label: "Phone Number",
    icon: Phone,
    href: "tel:+15551234567",
    description: "Call or text me",
    color: "bg-blue-600 hover:bg-blue-500",
  },
  {
    type: "location",
    value: "San Francisco, CA",
    label: "Location",
    icon: MapPin,
    href: "https://maps.google.com/?q=San+Francisco+CA",
    description: "Based in San Francisco",
    color: "bg-red-600 hover:bg-red-500",
  },
] as const;

// Working hours
export const WORKING_HOURS = [
  { day: "Monday - Friday", hours: "9:00 AM - 6:00 PM PST", available: true },
  { day: "Saturday", hours: "By appointment only", available: true },
  { day: "Sunday", hours: "Not available", available: false },
] as const;

// Color palette
export const COLORS = {
  primary: {
    light: "#16a34a",
    dark: "#15803d",
    gradient: "linear-gradient(135deg, #16a34a, #15803d)",
  },
  secondary: {
    light: "#f59e0b",
    dark: "#d97706",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
  },
  accent: {
    light: "#8b5cf6",
    dark: "#7c3aed",
    gradient: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
  },
  success: {
    light: "#10b981",
    dark: "#059669",
    gradient: "linear-gradient(135deg, #10b981, #059669)",
  },
  warning: {
    light: "#f59e0b",
    dark: "#d97706",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
  },
  error: {
    light: "#ef4444",
    dark: "#dc2626",
    gradient: "linear-gradient(135deg, #ef4444, #dc2626)",
  },
  info: {
    light: "#3b82f6",
    dark: "#2563eb",
    gradient: "linear-gradient(135deg, #3b82f6, #2563eb)",
  },
} as const;

// Animation durations
export const ANIMATION_DURATIONS = {
  fast: 150,
  medium: 300,
  slow: 500,
  verySlow: 1000,
  extraSlow: 2000,
} as const;

// Animation easings
export const ANIMATION_EASINGS = {
  linear: "linear",
  ease: "ease",
  easeIn: "ease-in",
  easeOut: "ease-out",
  easeInOut: "ease-in-out",
  cubicBezier: "cubic-bezier(0.4, 0, 0.2, 1)",
  bounce: "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
} as const;

// Breakpoints
export const BREAKPOINTS = {
  xs: 0,
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1536,
} as const;

// Z-index layers
export const Z_INDEX = {
  background: -1,
  base: 0,
  content: 10,
  navigation: 50,
  dropdown: 100,
  modal: 200,
  toast: 300,
  tooltip: 400,
  cursor: 500,
} as const;

// Typography
export const TYPOGRAPHY = {
  fontSizes: {
    xs: "0.75rem",
    sm: "0.875rem",
    base: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
    "6xl": "3.75rem",
    "7xl": "4.5rem",
    "8xl": "6rem",
    "9xl": "8rem",
  },
  fontWeights: {
    thin: 100,
    extralight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  lineHeights: {
    none: 1,
    tight: 1.25,
    snug: 1.375,
    normal: 1.5,
    relaxed: 1.625,
    loose: 2,
  },
  letterSpacing: {
    tighter: "-0.05em",
    tight: "-0.025em",
    normal: "0em",
    wide: "0.025em",
    wider: "0.05em",
    widest: "0.1em",
  },
} as const;

// Spacing
export const SPACING = {
  0: "0px",
  1: "0.25rem",
  2: "0.5rem",
  3: "0.75rem",
  4: "1rem",
  5: "1.25rem",
  6: "1.5rem",
  8: "2rem",
  10: "2.5rem",
  12: "3rem",
  16: "4rem",
  20: "5rem",
  24: "6rem",
  32: "8rem",
  40: "10rem",
  48: "12rem",
  56: "14rem",
  64: "16rem",
} as const;

// Border radius
export const BORDER_RADIUS = {
  none: "0px",
  sm: "0.125rem",
  base: "0.25rem",
  md: "0.375rem",
  lg: "0.5rem",
  xl: "0.75rem",
  "2xl": "1rem",
  "3xl": "1.5rem",
  full: "9999px",
} as const;

// Shadows
export const SHADOWS = {
  xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  sm: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  base: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  md: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  lg: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
  xl: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
  "2xl": "0 50px 100px -20px rgb(0 0 0 / 0.25)",
  inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
  glow: "0 0 20px rgba(22, 163, 74, 0.3)",
  "glow-lg": "0 0 40px rgba(22, 163, 74, 0.5)",
} as const;

// Marquee items
export const MARQUEE_ITEMS = [
  { id: "react", title: "React", category: "Frontend", color: "primary" },
  {
    id: "typescript",
    title: "TypeScript",
    category: "Language",
    color: "secondary",
  },
  { id: "nextjs", title: "Next.js", category: "Framework", color: "accent" },
  { id: "nodejs", title: "Node.js", category: "Backend", color: "primary" },
  { id: "aws", title: "AWS", category: "Cloud", color: "secondary" },
  { id: "docker", title: "Docker", category: "DevOps", color: "accent" },
  { id: "graphql", title: "GraphQL", category: "API", color: "primary" },
  { id: "mongodb", title: "MongoDB", category: "Database", color: "secondary" },
  {
    id: "kubernetes",
    title: "Kubernetes",
    category: "DevOps",
    color: "accent",
  },
  { id: "tailwind", title: "Tailwind CSS", category: "CSS", color: "primary" },
  { id: "python", title: "Python", category: "Language", color: "secondary" },
  { id: "go", title: "Go", category: "Language", color: "accent" },
  { id: "redis", title: "Redis", category: "Database", color: "primary" },
  {
    id: "terraform",
    title: "Terraform",
    category: "DevOps",
    color: "secondary",
  },
  {
    id: "postgresql",
    title: "PostgreSQL",
    category: "Database",
    color: "accent",
  },
] as const;

// Typewriter texts
export const TYPEWRITER_TEXTS = [
  "Full-Stack Developer",
  "System Architect",
  "Cloud Specialist",
  "UI/UX Enthusiast",
  "Problem Solver",
  "Tech Innovator",
  "Performance Optimizer",
  "Team Leader",
  "Open Source Contributor",
  "Mentor & Educator",
] as const;

// Features highlights
export const FEATURE_HIGHLIGHTS = [
  {
    icon: Zap,
    title: "Fast Learner",
    description:
      "Quickly adapt to new technologies and frameworks with proven track record",
    color: "primary",
    gradient: "from-emerald-500 to-green-500",
  },
  {
    icon: Rocket,
    title: "Performance Focus",
    description: "Optimize applications for speed, efficiency, and scalability",
    color: "secondary",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    icon: Shield,
    title: "Best Practices",
    description:
      "Follow industry standards, security guidelines, and clean code principles",
    color: "accent",
    gradient: "from-violet-500 to-purple-500",
  },
  {
    icon: Users,
    title: "Team Player",
    description:
      "Excellent collaboration skills and experience leading cross-functional teams",
    color: "primary",
    gradient: "from-cyan-500 to-blue-500",
  },
] as const;

// Experience timeline
export const EXPERIENCE_TIMELINE = [
  {
    id: "exp1",
    company: "Tech Innovations Inc.",
    position: "Senior Full-Stack Developer",
    period: "2022 - Present",
    description: [
      "Led development of scalable microservices architecture serving 1M+ users",
      "Implemented CI/CD pipelines reducing deployment time by 70%",
      "Optimized application performance achieving 95+ Lighthouse scores",
      "Mentored 5 junior developers and established coding standards",
    ],
    technologies: [
      "React",
      "Node.js",
      "AWS",
      "Docker",
      "Kubernetes",
      "GraphQL",
    ],
    current: true,
    logo: "/logos/tech-innovations.svg",
  },
  {
    id: "exp2",
    company: "Digital Solutions Co.",
    position: "Full-Stack Developer",
    period: "2020 - 2022",
    description: [
      "Developed and maintained multiple client projects using modern stack",
      "Built real-time dashboard for data visualization and analytics",
      "Integrated third-party APIs and payment gateways",
      "Improved application security and implemented best practices",
    ],
    technologies: ["Vue.js", "Python", "PostgreSQL", "Redis", "Docker"],
    current: false,
    logo: "/logos/digital-solutions.svg",
  },
  {
    id: "exp3",
    company: "Startup Ventures",
    position: "Frontend Developer",
    period: "2018 - 2020",
    description: [
      "Built responsive web applications with React and TypeScript",
      "Collaborated with design team to implement pixel-perfect UIs",
      "Optimized website performance and accessibility",
      "Participated in agile development processes",
    ],
    technologies: ["React", "TypeScript", "Redux", "SASS", "Jest"],
    current: false,
    logo: "/logos/startup-ventures.svg",
  },
] as const;

// Education
export const EDUCATION = [
  {
    id: "edu1",
    institution: "Stanford University",
    degree: "Master of Science",
    field: "Computer Science",
    period: "2016 - 2018",
    grade: "3.9/4.0 GPA",
    logo: "/logos/stanford.svg",
  },
  {
    id: "edu2",
    institution: "MIT",
    degree: "Bachelor of Science",
    field: "Software Engineering",
    period: "2012 - 2016",
    grade: "Summa Cum Laude",
    logo: "/logos/mit.svg",
  },
] as const;

// Testimonials
export const TESTIMONIALS = [
  {
    id: "test1",
    name: "Sarah Johnson",
    role: "CTO",
    company: "TechCorp Inc.",
    content:
      "Yohannes delivered exceptional work on our platform migration. His expertise in cloud architecture and attention to detail were instrumental in our success.",
    avatar: "/avatars/sarah.jpg",
    rating: 5,
    date: "2023-12-15",
  },
  {
    id: "test2",
    name: "Michael Chen",
    role: "Product Manager",
    company: "Innovate Labs",
    content:
      "Working with Yohannes was a pleasure. He consistently delivered high-quality code and provided valuable insights that improved our product.",
    avatar: "/avatars/michael.jpg",
    rating: 5,
    date: "2023-10-22",
  },
  {
    id: "test3",
    name: "Alexandra Williams",
    role: "Lead Designer",
    company: "Creative Minds",
    content:
      "Yohannes understands the balance between beautiful design and technical implementation. His frontend skills are top-notch.",
    avatar: "/avatars/alexandra.jpg",
    rating: 5,
    date: "2023-08-30",
  },
] as const;

// Metrics
export const METRICS = [
  { label: "Projects Completed", value: "150+", icon: Briefcase },
  { label: "Happy Clients", value: "50+", icon: Heart },
  { label: "Years Experience", value: "6+", icon: Calendar },
  { label: "Technologies", value: "25+", icon: Code },
] as const;

// SEO metadata
export const SEO_METADATA = {
  title: "Yohannes Belete | Senior Full-Stack Developer & System Architect",
  description:
    "Building exceptional digital experiences with modern technologies. Specializing in full-stack development, cloud architecture, and performance optimization.",
  keywords: [
    "full-stack developer",
    "system architect",
    "react developer",
    "next.js developer",
    "typescript developer",
    "aws architect",
    "devops engineer",
    "san francisco developer",
    "software engineer",
    "web developer",
    "cloud architect",
    "performance optimization",
    "scalable applications",
    "microservices",
    "modern web development",
  ],
  author: "Yohannes Belete",
  url: "https://yohannesbelete.dev",
  image: "/og-image.jpg",
  locale: "en_US",
  type: "website",
} as const;

// Accessibility labels
export const ACCESSIBILITY_LABELS = {
  navigation: "Main navigation",
  skipToContent: "Skip to main content",
  themeToggle: "Toggle theme",
  languageToggle: "Toggle language",
  closeMenu: "Close menu",
  openMenu: "Open menu",
  closeModal: "Close modal",
  openModal: "Open modal",
  previousSlide: "Previous slide",
  nextSlide: "Next slide",
  playAnimation: "Play animation",
  pauseAnimation: "Pause animation",
  volumeToggle: "Toggle volume",
  fullscreenToggle: "Toggle fullscreen",
  loading: "Loading",
  loaded: "Loaded",
  error: "Error",
  success: "Success",
  warning: "Warning",
  info: "Information",
} as const;

// Performance metrics
export const PERFORMANCE_TARGETS = {
  fcp: 1000, // First Contentful Paint (ms)
  lcp: 2500, // Largest Contentful Paint (ms)
  fid: 100, // First Input Delay (ms)
  cls: 0.1, // Cumulative Layout Shift
  tti: 3800, // Time to Interactive (ms)
  tbt: 300, // Total Blocking Time (ms)
} as const;
